import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { manifests } from '../layers/plugin-manifests'
import type { PluginModuleManifest } from '../layers/_shared/module-manifest'

function uniq<T>(arr: T[]): T[] {
  return Array.from(new Set(arr))
}

function generate() {
  const typedManifests = manifests as PluginModuleManifest[]

  const moduleKeys = typedManifests.map((m) => m.module.key)
  const permissionKeys = uniq(typedManifests.flatMap((m) => m.permissions.map((p) => p.key)))

  // Modulroller borttagna; behåll struktur för bakåtkomp men som tomma listor
  const moduleRolesMap: Record<string, string[]> = {}
  for (const m of typedManifests) {
    moduleRolesMap[m.module.key] = []
  }

  const moduleKeyUnion = moduleKeys.map((k) => `'${k}'`).join(' | ') || 'never'
  const permissionKeyUnion = permissionKeys.map((k) => `'${k}'`).join(' | ') || 'never'

  const moduleRoleMapEntries = Object.entries(moduleRolesMap)
    .map(([moduleKey, roles]) => {
      const roleUnion = roles.map((r) => `'${r}'`).join(' | ') || 'never'
      return `  '${moduleKey}': ${roleUnion};`
    })
    .join('\n')

  const moduleRolePairs: string[] = []
  for (const [moduleKey, roles] of Object.entries(moduleRolesMap)) {
    for (const role of roles) {
      moduleRolePairs.push(`'${moduleKey}:${role}'`)
    }
  }
  const moduleRoleKeyUnion = moduleRolePairs.join(' | ') || 'never'

  const content = `// AUTO-GENERATED BY scripts/generate-rbac-types.ts
// Do not edit manually.

export type ModuleKey = ${moduleKeyUnion}

export type PermissionKey = ${permissionKeyUnion}

export interface ModuleRoleKeyMap {
${moduleRoleMapEntries}
}

export type ModuleRoleKey = ${moduleRoleKeyUnion}
`

  const dir = path.dirname(fileURLToPath(import.meta.url))
  const outPath = path.join(dir, '..', 'app', 'generated', 'rbac-types.ts')
  fs.mkdirSync(path.dirname(outPath), { recursive: true })
  fs.writeFileSync(outPath, content, 'utf8')

  console.log(`Generated RBAC types to: ${outPath}`)
}

generate()
