// Generate Layer Schemas + Plugin Manifests
//
// Scans layers/ for:
//   1. layers with server/database/index.ts exporting createSchema
//      → generates server/database/layer-schemas.generated.ts
//   2. layers with module.manifest.ts
//      → generates layers/plugin-manifests.generated.ts
//
// Both outputs use static imports so they work in client and server bundles
// without pulling in node:fs at runtime.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const layersDir = path.resolve(__dirname, '..', 'layers')
const schemasOutPath = path.resolve(__dirname, '..', 'server', 'database', 'layer-schemas.generated.ts')
const manifestsOutPath = path.resolve(__dirname, '..', 'layers', 'plugin-manifests.ts')

interface LayerWithSchema {
  name: string
  factoryName: string
}

interface LayerWithManifest {
  name: string
  varName: string
}

function toCamelCase(name: string): string {
  return name
    .split('-')
    .map((part, i) => (i === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join('')
}

function isLayerDir(name: string): boolean {
  return !name.startsWith('_') && !name.startsWith('.') && name !== 'plugin-template'
}

function discoverLayersWithSchemas(): LayerWithSchema[] {
  const entries = fs.readdirSync(layersDir, { withFileTypes: true })
  const layers: LayerWithSchema[] = []

  for (const entry of entries) {
    if (!entry.isDirectory() || !isLayerDir(entry.name)) continue

    const indexPath = path.resolve(layersDir, entry.name, 'server', 'database', 'index.ts')
    if (!fs.existsSync(indexPath)) continue

    // Check if index.ts exports createSchema
    const content = fs.readFileSync(indexPath, 'utf8')
    if (!content.includes('createSchema')) continue

    const camelName = toCamelCase(entry.name)
    layers.push({
      name: entry.name,
      factoryName: `create${camelName.charAt(0).toUpperCase() + camelName.slice(1)}Schema`
    })
  }

  return layers
}

function discoverLayersWithManifests(): LayerWithManifest[] {
  const entries = fs.readdirSync(layersDir, { withFileTypes: true })
  const layers: LayerWithManifest[] = []

  for (const entry of entries) {
    if (!entry.isDirectory() || !isLayerDir(entry.name)) continue

    const manifestPath = path.resolve(layersDir, entry.name, 'module.manifest.ts')
    if (!fs.existsSync(manifestPath)) continue

    const camelName = toCamelCase(entry.name)
    layers.push({
      name: entry.name,
      varName: `${camelName}Manifest`
    })
  }

  return layers
}

function generateLayerSchemas() {
  const layers = discoverLayersWithSchemas()

  const imports = layers
    .map(l => `import { createSchema as ${l.factoryName} } from '../../layers/${l.name}/server/database'`)
    .join('\n')

  const spreadEntries = layers
    .map(l => `    ...${l.factoryName}(organizationsId)`)
    .join(',\n')

  const content = `// AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-layer-schemas.ts
import type { AnyMySqlColumn } from 'drizzle-orm/mysql-core'

${imports}

export function createAllLayerSchemas(organizationsId: AnyMySqlColumn) {
  return {
${spreadEntries}
  }
}
`

  fs.writeFileSync(schemasOutPath, content, 'utf8')
  console.log(`Generated layer schemas to: ${schemasOutPath}`)
  console.log(`  Discovered ${layers.length} layer(s): ${layers.map(l => l.name).join(', ')}`)
}

function generatePluginManifests() {
  const layers = discoverLayersWithManifests()

  const imports = layers
    .map(l => `import ${l.varName} from './${l.name}/module.manifest'`)
    .join('\n')

  const arrayEntries = layers
    .map(l => `  ${l.varName}`)
    .join(',\n')

  const content = `// AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-layer-schemas.ts
import type { PluginModuleManifest } from './_shared/module-manifest'

${imports}

export const manifests: PluginModuleManifest[] = [
${arrayEntries}
]
`

  fs.writeFileSync(manifestsOutPath, content, 'utf8')
  console.log(`Generated plugin manifests to: ${manifestsOutPath}`)
  console.log(`  Discovered ${layers.length} manifest(s): ${layers.map(l => l.name).join(', ')}`)
}

generateLayerSchemas()
generatePluginManifests()
