namespace CertAgent.Worker.Helpers;

/// <summary>
/// Generates temp PS1 scripts for DNS-01 challenge automation via the portal.
/// Scripts NEVER contain secrets — the challenge token is read from an
/// ACL-protected file at runtime and sent only as a Bearer header.
/// </summary>
public static class DnsChallengeScriptGenerator
{
    private const string CreateScriptTemplate = @"# DNS-01 challenge create script (auto-generated by cert-agent)
# simple-acme passes: Identifier RecordName Token as positional args
param(
    [Parameter(Position=0)][string]$Identifier,
    [Parameter(Position=1)][string]$RecordName,
    [Parameter(Position=2)][string]$Token
)
# Fallback to env vars if positional args are empty
if (-not $Identifier) {{ $Identifier = $env:SIMPLE_ACME_IDENTIFIER }}
if (-not $RecordName) {{ $RecordName = $env:SIMPLE_ACME_RECORDNAME }}
if (-not $Token)      {{ $Token = $env:SIMPLE_ACME_TOKEN }}

$challengeToken = (Get-Content -Path ""{0}"" -Raw).Trim()
$headers = @{{
    Authorization  = ""Bearer $challengeToken""
    'Content-Type' = 'application/json'
}}
$body = @{{
    action         = ""create""
    recordName     = $RecordName
    challengeValue = $Token
}} | ConvertTo-Json
Invoke-RestMethod -Uri ""{1}/api/certificates/agent-api/dns-challenge"" `
    -Method POST -Headers $headers -Body $body
";

    private const string DeleteScriptTemplate = @"# DNS-01 challenge delete script (auto-generated by cert-agent)
param(
    [Parameter(Position=0)][string]$Identifier,
    [Parameter(Position=1)][string]$RecordName,
    [Parameter(Position=2)][string]$Token
)
if (-not $Identifier) {{ $Identifier = $env:SIMPLE_ACME_IDENTIFIER }}
if (-not $RecordName) {{ $RecordName = $env:SIMPLE_ACME_RECORDNAME }}
if (-not $Token)      {{ $Token = $env:SIMPLE_ACME_TOKEN }}

$challengeToken = (Get-Content -Path ""{0}"" -Raw).Trim()
$headers = @{{
    Authorization  = ""Bearer $challengeToken""
    'Content-Type' = 'application/json'
}}
$body = @{{
    action         = ""delete""
    recordName     = $RecordName
    challengeValue = $Token
}} | ConvertTo-Json
Invoke-RestMethod -Uri ""{1}/api/certificates/agent-api/dns-challenge"" `
    -Method POST -Headers $headers -Body $body
";

    /// <summary>
    /// Generate create/delete PS1 scripts and write the challenge token to a secret file.
    /// Scripts read the token from the secret file at execution time — no embedded secrets.
    /// </summary>
    public static DnsChallengeFiles Generate(string portalBaseUrl, string dnsChallengeToken)
    {
        var basePath = Path.Combine(Path.GetTempPath(), $"certagent-dns-{Guid.NewGuid():N}");

        var tokenFilePath = basePath + ".token";
        var createScriptPath = basePath + "-create.ps1";
        var deleteScriptPath = basePath + "-delete.ps1";

        // Write challenge token to ACL-protected file
        // Reuse SecretFileHelper pattern but write to specific path
        File.WriteAllText(tokenFilePath, dnsChallengeToken);
        ApplyRestrictiveAcl(tokenFilePath);
        LogRedactor.AddDynamicPattern(dnsChallengeToken, "[DNS_CHALLENGE_TOKEN]");
        LogRedactor.AddDynamicPattern(tokenFilePath, "[DNS_TOKEN_FILE]");

        // Normalize portal URL (remove trailing slash)
        var baseUrl = portalBaseUrl.TrimEnd('/');

        // Generate scripts with token file path and portal URL embedded (not secrets)
        var createScript = string.Format(CreateScriptTemplate, tokenFilePath, baseUrl);
        var deleteScript = string.Format(DeleteScriptTemplate, tokenFilePath, baseUrl);

        File.WriteAllText(createScriptPath, createScript);
        File.WriteAllText(deleteScriptPath, deleteScript);

        LogRedactor.AddDynamicPattern(createScriptPath, "[DNS_CREATE_SCRIPT]");
        LogRedactor.AddDynamicPattern(deleteScriptPath, "[DNS_DELETE_SCRIPT]");

        return new DnsChallengeFiles
        {
            CreateScriptPath = createScriptPath,
            DeleteScriptPath = deleteScriptPath,
            TokenFilePath = tokenFilePath
        };
    }

    /// <summary>
    /// Clean up all generated files (scripts + token file).
    /// Safe to call with null — no-op.
    /// </summary>
    public static void Cleanup(DnsChallengeFiles? files)
    {
        if (files == null) return;

        SecretFileHelper.DeleteSecretFile(files.TokenFilePath);
        SecretFileHelper.DeleteSecretFile(files.CreateScriptPath);
        SecretFileHelper.DeleteSecretFile(files.DeleteScriptPath);
    }

    private static void ApplyRestrictiveAcl(string path)
    {
        try
        {
            var fileInfo = new FileInfo(path);
            var security = fileInfo.GetAccessControl();
            security.SetAccessRuleProtection(isProtected: true, preserveInheritance: false);

            var currentUser = System.Security.Principal.WindowsIdentity.GetCurrent().User;
            if (currentUser != null)
            {
                var rules = security.GetAccessRules(true, true, typeof(System.Security.Principal.SecurityIdentifier));
                foreach (System.Security.AccessControl.FileSystemAccessRule rule in rules)
                {
                    security.RemoveAccessRule(rule);
                }
                security.AddAccessRule(new System.Security.AccessControl.FileSystemAccessRule(
                    currentUser,
                    System.Security.AccessControl.FileSystemRights.FullControl,
                    System.Security.AccessControl.AccessControlType.Allow));
                fileInfo.SetAccessControl(security);
            }
        }
        catch
        {
            // ACL restriction is defense-in-depth; don't fail the operation
        }
    }
}

/// <summary>
/// Paths to the generated DNS challenge files.
/// </summary>
public sealed class DnsChallengeFiles
{
    public required string CreateScriptPath { get; init; }
    public required string DeleteScriptPath { get; init; }
    public required string TokenFilePath { get; init; }
}
