import { eq, and } from 'drizzle-orm'
import { getRouterParam, getRequestURL, setHeader } from 'h3'
import { ensureAuthState } from '~~/server/utils/session'
import { getDb } from '~~/server/utils/db'
import { getCertificatesModuleAccessForUser } from '../../../../lib/certificates/access'
import { certAgents } from '~~/server/database/schema'

export default defineEventHandler(async (event) => {
  const auth = await ensureAuthState(event)
  if (!auth?.currentOrgId) {
    throw createError({ statusCode: 400, message: 'Organisation saknas i sessionen.' })
  }
  const orgId = auth.currentOrgId
  const id = getRouterParam(event, 'id')
  if (!id) throw createError({ statusCode: 400, message: 'Missing agent ID.' })

  if (!auth.user.isSuperAdmin) {
    const access = await getCertificatesModuleAccessForUser(orgId, auth.user.id)
    if (!access.canManageAgents && !access.canAdmin) {
      throw createError({ statusCode: 403, message: 'Missing permission to manage agents.' })
    }
  }

  const db = getDb()
  const [agent] = await db
    .select()
    .from(certAgents)
    .where(and(eq(certAgents.id, id), eq(certAgents.organizationId, orgId)))

  if (!agent) {
    throw createError({ statusCode: 404, message: 'Agent not found.' })
  }

  const requestUrl = getRequestURL(event)
  const portalBaseUrl = `${requestUrl.protocol}//${requestUrl.host}`
  const safeName = agent.name.replace(/[^a-zA-Z0-9_-]/g, '_')

  setHeader(event, 'Content-Type', 'text/plain; charset=utf-8')
  setHeader(event, 'Content-Disposition', `attachment; filename="Install-CertAgent-${safeName}.ps1"`)

  return `#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Installs the CertAgent Windows service for "${agent.name}".

.DESCRIPTION
    Copies published agent files, writes configuration, and installs as a Windows service.
    Generated by CloudPortal MSP — ${portalBaseUrl}

.PARAMETER AgentToken
    The agent authentication token (required). Obtain from the portal.

.PARAMETER InstallPath
    Destination folder for the service files. Default: C:\\Services\\CertAgent

.PARAMETER AgentSourcePath
    Path to the published agent build output. Default: .\\publish
#>
param(
    [Parameter(Mandatory = $true)]
    [string]$AgentToken,

    [Parameter()]
    [string]$InstallPath = "C:\\Services\\CertAgent",

    [Parameter()]
    [string]$AgentSourcePath = ".\\publish"
)

$ErrorActionPreference = "Stop"
$ServiceName = "CertAgent"
$ServiceDisplayName = "CertAgent - ${agent.name}"
$PortalBaseUrl = "${portalBaseUrl}"

Write-Host "=== CertAgent Installer ===" -ForegroundColor Cyan
Write-Host "Agent: ${agent.name}"
Write-Host "Portal: $PortalBaseUrl"
Write-Host ""

# --- Validate token format ---
if (-not $AgentToken.StartsWith("msp_agent.")) {
    Write-Error "Invalid token format. Token must start with 'msp_agent.'"
    exit 1
}
Write-Host "[OK] Token format valid" -ForegroundColor Green

# --- Validate source path ---
if (-not (Test-Path "$AgentSourcePath\\CertAgent.exe" -PathType Leaf)) {
    # Also check for dll-based deployment
    if (-not (Test-Path "$AgentSourcePath\\CertAgent.dll" -PathType Leaf)) {
        Write-Error "Cannot find CertAgent.exe or CertAgent.dll in '$AgentSourcePath'. Build the agent first with 'dotnet publish -c Release -o publish'."
        exit 1
    }
}
Write-Host "[OK] Source files found at $AgentSourcePath" -ForegroundColor Green

# --- Stop existing service if running ---
$existingSvc = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existingSvc) {
    Write-Host "Stopping existing $ServiceName service..." -ForegroundColor Yellow
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
}

# --- Copy files ---
Write-Host "Copying files to $InstallPath..."
if (-not (Test-Path $InstallPath)) {
    New-Item -ItemType Directory -Path $InstallPath -Force | Out-Null
}
Copy-Item -Path "$AgentSourcePath\\*" -Destination $InstallPath -Recurse -Force
Write-Host "[OK] Files copied" -ForegroundColor Green

# --- Write appsettings.json ---
$appSettings = @{
    Logging = @{
        LogLevel = @{
            Default = "Information"
            "Microsoft.Hosting.Lifetime" = "Information"
        }
    }
    AgentOptions = @{
        PortalBaseUrl = $PortalBaseUrl
        AgentToken = $AgentToken
        HeartbeatIntervalSeconds = 60
        PollIntervalSeconds = 30
        WacsPath = "C:\\simple-acme\\wacs.exe"
    }
} | ConvertTo-Json -Depth 4

$appSettingsPath = Join-Path $InstallPath "appsettings.json"
Set-Content -Path $appSettingsPath -Value $appSettings -Encoding UTF8
Write-Host "[OK] Configuration written to $appSettingsPath" -ForegroundColor Green

# --- Install Windows service ---
$exePath = Join-Path $InstallPath "CertAgent.exe"
if (-not (Test-Path $exePath)) {
    Write-Error "CertAgent.exe not found at $exePath"
    exit 1
}

if ($existingSvc) {
    Write-Host "Updating existing service..." -ForegroundColor Yellow
    sc.exe config $ServiceName binPath= "\`"$exePath\`"" | Out-Null
} else {
    Write-Host "Creating Windows service..."
    sc.exe create $ServiceName binPath= "\`"$exePath\`"" start= delayed-auto DisplayName= "\`"$ServiceDisplayName\`"" | Out-Null
}
sc.exe failure $ServiceName reset= 86400 actions= restart/5000/restart/10000/restart/30000 | Out-Null
Write-Host "[OK] Service installed with automatic restart on failure" -ForegroundColor Green

# --- Check simple-acme ---
$wacsPath = "C:\\simple-acme\\wacs.exe"
if (Test-Path $wacsPath) {
    Write-Host "[OK] simple-acme found at $wacsPath" -ForegroundColor Green
} else {
    Write-Host "[WARN] simple-acme not found at $wacsPath" -ForegroundColor Yellow
    Write-Host "       Download from https://simple-acme.com and extract to C:\\simple-acme\\" -ForegroundColor Yellow
}

# --- Start service ---
Write-Host "Starting $ServiceName..."
Start-Service -Name $ServiceName
Start-Sleep -Seconds 3
$svc = Get-Service -Name $ServiceName
if ($svc.Status -eq "Running") {
    Write-Host "[OK] Service is running" -ForegroundColor Green
} else {
    Write-Host "[WARN] Service status: $($svc.Status)" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "=== Installation complete ===" -ForegroundColor Cyan
Write-Host "The agent should appear online in the portal within 60 seconds."
Write-Host "Portal URL: $PortalBaseUrl/certificates/agents"
`
})
