// AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-layer-schemas.ts
import type { AnyMySqlColumn } from 'drizzle-orm/mysql-core'

import { createSchema as createCertificatesSchema } from '../../layers/certificates/server/database'
import { createSchema as createCloudflareDnsSchema } from '../../layers/cloudflare-dns/server/database'
import { createSchema as createWindowsDnsSchema } from '../../layers/windows-dns/server/database'
import { createSchema as createWindowsDnsRedirectsSchema } from '../../layers/windows-dns-redirects/server/database'

export function createAllLayerSchemas(organizationsId: AnyMySqlColumn) {
  return {
    ...createCertificatesSchema(organizationsId),
    ...createCloudflareDnsSchema(organizationsId),
    ...createWindowsDnsSchema(organizationsId),
    ...createWindowsDnsRedirectsSchema(organizationsId)
  }
}
