// AUTO-GENERATED — DO NOT EDIT
// Generated by scripts/generate-layer-schemas.ts
import type { PluginModuleManifest } from './_shared/module-manifest'

import certificatesManifest from './certificates/module.manifest'
import cloudflareDnsManifest from './cloudflare-dns/module.manifest'
import windowsDnsManifest from './windows-dns/module.manifest'

export const manifests: PluginModuleManifest[] = [
  certificatesManifest,
  cloudflareDnsManifest,
  windowsDnsManifest
]
